version: "3"
services:
  platform:
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - pasquali-network

  db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/data
    environment:
      POSTGRES_DB: pasquali
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - pasquali-network

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 3333:3333
    command:
      - node
      - index.js

      - knex migrate:latest
    networks:
      - pasquali-network

volumes:
  postgres-data: {}

networks:
  pasquali-network:
    external: true